### PR TITLE
2.1 development

### PR DESCRIPTION
**Pull request by Reedyn**

### CODE REVIEW

**Comment by Badmonky** [comment]
hi there, looks like this PR has the membership feature i am looking for enabled... could you merge this and release version 2.1? Would love to use your theme, but need the membership part

**Comment by Reedyn** [comment]
> hi there, looks like this PR has the membership feature i am looking for enabled... could you merge this and release version 2.1? Would love to use your theme, but need the membership part 
> 

What feature are you talking about? And it's not 100% ready yet. More like 90% ready.

If you want to use in current state there is a prerelease version you can try

**Comment by Badmonky** [comment]
> > hi there, looks like this PR has the membership feature i am looking for enabled... could you merge this and release version 2.1? Would love to use your theme, but need the membership part
> 
> What feature are you talking about? And it's not 100% ready yet. More like 90% ready.
> 
> If you want to use in current state there is a prerelease version you can try

Thanks for the fast reply. 

I saw the commit "Added Subscriber Feature", which i assumed would anable the membership functionality ghost now has. Essentially i'd like to be able to control all or part of the blog to only be visible to members (paid or not does not matter for me yet. Just try to keep an eye on who is reading. ;) But of course if it could be monetized in the future. That would be cool. 

I saw the RC4 just now, and going to try it out. Thanks again

**Comment by Reedyn** [comment]
I did not add a dedicated subscriber button. Instead any link with the url `#subscribe` will trigger the overlay

**Comment by Badmonky** [comment]
Saw the overlay. Any way to style that? Also, I assume that requires the mailgun integration to be fully setup already for it to work?  And is that only for the newsletter? Or do you have a way to let members login as well already (if no, any pans to add that?)

**Comment by Reedyn** [comment]
There should be enough classes for you to style everything so just add some of your own code to ghost_head and override.

The mail feature depends how you host it. Personally i use Ghost Pro so I don't think about that much. Its all back-end though

**Comment by Badmonky** [comment]
Gotcha on the styling.
I hosted it on my server. But they have the membership section integrated now under Labs, and there is an email settings section, which i assumed would be part of the subscribe / member section. 

So sounds like no plans to support the membership functionality yet? (like so: https://ghost.org/docs/members/signup-signin-forms/)

**Comment by Reedyn** [comment]
In the release after 2.1 all the styling will be defined using css variables, so it will be much easier to change the theme and colors.

**Comment by Reedyn** [comment]
> Gotcha on the styling.
> I hosted it on my server. But they have the membership section integrated now under Labs, and there is an email settings section, which i assumed would be part of the subscribe / member section. 
> 
> So sounds like no plans to support the membership functionality yet? (like so: https://ghost.org/docs/members/signup-signin-forms/) 
> 

The theme will and does (the pre-release) support membership. All the theme does is display the form and notifications for subscribing. Everything else is under the hood and has nothing to do with the activated theme.

**Comment by Badmonky** [comment]
> > Gotcha on the styling.
> > I hosted it on my server. But they have the membership section integrated now under Labs, and there is an email settings section, which i assumed would be part of the subscribe / member section.
> > So sounds like no plans to support the membership functionality yet? (like so: https://ghost.org/docs/members/signup-signin-forms/)
> 
> The theme will and does (the pre-release) support membership. All the theme does is display the form and notifications for subscribing. Everything else is under the hood and has nothing to do with the activated theme.

right. I just could not find any implementation for the sign up / sign in forms, which is why I asked. I would not know how to let the users sign in with the current RC4 (at least could not find anything when searching through the code.

**Pull request merged**
