### PR TITLE
rewrote scripts.js in a more modular fashion

### PR DESCRIPTION
**Pull request by wemakeweb**
Pull Request for: https://github.com/Reedyn/Saga/issues/76

### CODE REVIEW

**Comment by Reedyn** [comment]
Very beautiful! Will do some quick testing when I get home. Let me know when you think it's ready to merge. Thank you again =)

**Comment by wemakeweb** [comment]
Waaa, i tried to fix the code style issues, but failed :D . I added the option `scriptsPresent` so we can later bundle the front end files.

**Comment by wemakeweb** [comment]
If your testing passes, we are good to merge :+1:

**Comment by wemakeweb** [comment]
status?

**Pull request merged**
